steps:
  - name: ubuntu
    args:
      - echo
      - $SHORT_SHA
  - name: ubuntu
    args:
      - echo
      # You can pass values for variables from Terraform to the yaml config like so:
      - ${test} 
timeout: 600s
